// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brlytrxzzvrxamnqhako.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJybHl0cnh6enZyeGFtbnFoYWtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3MjkyNzUsImV4cCI6MjA1NTMwNTI3NX0.X4xdJJ0twgxg1E7tLxNTkbrOEEqNlNtKNgNCobV5Fzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);